build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit test/* --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'clover'
